services:
  loadbalancer:
    image: nginx
    restart: always
    ports:
      - 8080:80 # client can do `curl localhost:8080`
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  slow_service:
    image: nginx_demo/slow_service
    restart: unless-stopped # Default: no
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command:
      - -c
      - |
        while true; do
          payload="HTTP/1.1 200 OK\n\n Hello World (from $$(hostname -i))!"
          echo -e $${payload} | ncat -v -l -p 80
          sleep 1  # Make slow service
        done
    depends_on:
      loadbalancer:
        condition: service_started
        restart: true
    deploy:
      replicas: 5

  debug:
    # debug client can do `curl slow_service`
    image: nginx_demo/debug
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sleep
    command: infinity
    deploy:
      replicas: 1
